@baseUrl = http://localhost:3000
@articleUrl = /articles
@testId = /31
@commentUrl = /comments
@testCommentId = /11

###등록
POST {{baseUrl}}{{articleUrl}}
Content-Type: application/json

{
  "title": "자유 게시판에 올라갈 게시물 제목",
  "content": "자유 게시판에 올라갈 게시물의 내용입니다. 자유 게시판에 올라갈 게시물의 내용입니다."
}

###상세 조회
GET {{baseUrl}}{{articleUrl}}{{testId}}

###수정
PATCH {{baseUrl}}{{articleUrl}}{{testId}}
Content-Type: application/json

{
  "title": "자유자유자유자유게시판판판"
}

###삭제
DELETE {{baseUrl}}{{articleUrl}}{{testId}}
Content-Type: application/json

###목록 조회 (10개)
GET {{baseUrl}}{{articleUrl}}

###목록 조회 (검색)
GET {{baseUrl}}{{articleUrl}}?search=자유

###목록 조회 (pagination)
GET {{baseUrl}}{{articleUrl}}?limit=10

###댓글 조회 
GET {{baseUrl}}{{articleUrl}}{{testId}}{{commentUrl}}

###댓글 생성 
POST {{baseUrl}}{{articleUrl}}{{testId}}{{commentUrl}}
Content-Type: application/json

{
  "content": "자유게시판의 댓글 6입니다"
}

###댓글 수정
PATCH {{baseUrl}}{{commentUrl}}{{testCommentId}}
Content-Type: application/json

{
  "content": "자유게시판의 수정한 댓글입니다"
}

###댓글 삭제
DELETE {{baseUrl}}{{commentUrl}}{{testCommentId}}
Content-Type: application/json