@baseUrl = http://localhost:3001
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4MzMyMTM4MiwiZXhwIjoxNzgzMzI0OTgyfQ.fGedkumY5CedmKi0KnPvn5bsw-p39aRbUzZ08qV6txk
POST {{baseUrl}}/products/9/like
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 상품 좋아요 -1
DELETE {{baseUrl}}/products/5/like
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###상품 상세 조회
GET {{baseUrl}}/products/2
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###좋아요 누른 상품들 조회
GET {{baseUrl}}/users/me/likes?page=1&pageSize=10&keyword=맥북
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###게시물 좋아요 +1
POST {{baseUrl}}/articles/5/like
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###게시물 좋아요 -1
DELETE {{baseUrl}}/articles/5/like
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###게시물 상세 조회
GET {{baseUrl}}/articles/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json
