@baseUrl = http://localhost:3001
@productUrl = /products
@testId =/220
@upsertId = /10001
@commentUrl = /comments
@testCommentId = /34

###등록
POST {{baseUrl}}{{productUrl}}
Content-Type: application/json

{
  "name": "비타민D",
  "description" : "몸에 좋은 비타민D 입니다!",
  "price": "100000",
  "tags": ["식품", "영양제"]
}

###상세 조회
GET {{baseUrl}}{{productUrl}}{{testId}}

###수정
PATCH {{baseUrl}}{{productUrl}}{{testId}}
Content-Type: application/json

{
  "name": "테슬라 자동차"
}

###upsert 테스트 - 있는 아이디
PUT {{baseUrl}}{{productUrl}}{{testId}}
Content-Type: application/json

{
  "name": "비타민D",
  "description" : "몸에 좋은 비타민D 입니다!",
  "price": "100000",
  "tags": ["식품", "영양제"]
}

###upsert 테스트 - 없는 아이디
PUT {{baseUrl}}{{productUrl}}{{upsertId}}
Content-Type: application/json

{
  "name": "비타민D",
  "description" : "몸에 좋은 비타민D 입니다!",
  "price": "100000",
  "tags": ["식품", "영양제"]
}

###삭제
DELETE {{baseUrl}}{{productUrl}}{{testId}}
Content-Type: application/json

###목록 조회 (10개)
GET {{baseUrl}}{{productUrl}}

###목록 조회 (검색)
GET {{baseUrl}}{{productUrl}}?search=테슬라

###목록 조회 (pagination)
GET {{baseUrl}}{{productUrl}}?limit=10

###댓글 조회 
GET {{baseUrl}}{{productUrl}}{{testId}}{{commentUrl}}

###댓글 생성 
POST {{baseUrl}}{{productUrl}}{{testId}}{{commentUrl}}
Content-Type: application/json

{
  "content": "중고마켓의 댓글 5입니다"
}

###댓글 수정
PATCH {{baseUrl}}{{commentUrl}}{{testCommentId}}
Content-Type: application/json

{
  "content": "중고마켓의 수정한 댓글입니다"
}

###댓글 삭제
DELETE {{baseUrl}}{{commentUrl}}{{testCommentId}}
Content-Type: application/json