@baseUrl = http://localhost:3001

###회원가입하기
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "unin5412@gmail.com",
  "nickname": "김은진",
  "password": "123456789",
  "passwordConfirm": "123456789"
}

###로그인하기
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "unin5412@gmail.com",
  "password": "123456789"
}