@baseUrl = http://localhost:3001
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJpYXQiOjE3ODM0ODc3MTEsImV4cCI6MTc4MzQ5MTMxMX0.WvcckSw6BKn9wuQfYlmIpoAl9Z3pIA3Ot9G6PBot7G4

###회원가입하기
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "snake@gmail.com",
  "nickname": "뱀뱀",
  "password": "123456789",
  "passwordConfirmation": "123456789"
}

###회원가입하기 - 일부 필드 누락
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "duckk@gmail.com",
  "nickname": "",
  "password": "",
  "passwordConfirmation": "123456789"
}

###로그인하기
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "snake@gmail.com",
  "password": "123456789"
}

###로그인하기
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "duck@gmail.com",
  "password": "123456789"
}

###내 정보 가져오기
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###상품 accessToken으로 등록
POST {{baseUrl}}/products
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "맥북 에어 M2",
  "description": "미개봉 새상품 맥북 에어 팝니다.",
  "price": 1200000
}

###상품 조회
GET {{baseUrl}}/products
Content-Type: application/json

###상품 accessToken으로 수정
PATCH {{baseUrl}}/products/34
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "개봉만 해본 새상품 맥북 에어 팝니다."
}

###상품 accessToken으로 삭제
DELETE {{baseUrl}}/products/34
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###게시물 accessToken으로 등록
POST {{baseUrl}}/articles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "맥북 에어 M2 얼마정도에 팔 수 있을까요?",
  "content": "개봉만 해본 상품인데 가격이 궁금해요"
}

###게시물 accessToken으로 수정
PATCH {{baseUrl}}/articles/18
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "개봉만 한 맥북 에어 M2 얼마정도에 팔 수 있을까요?"
}

###게시물 accessToken으로 삭제
DELETE {{baseUrl}}/articles/18
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###댓글 등록
POST {{baseUrl}}/products/17/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "저도 궁금해요!"
}

###댓글 조회
GET {{baseUrl}}/products/17/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###댓글 수정
PATCH {{baseUrl}}/comments/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "저도 궁금해요!!"
}

###댓글 삭제
DELETE {{baseUrl}}/comments/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###댓글 등록
POST {{baseUrl}}/articles/14/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "저도 궁금해요"
}

###댓글 조회
GET {{baseUrl}}/articles/14/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###댓글 수정
PATCH {{baseUrl}}/comments/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "content": "저도 궁금해요!!"
}

###댓글 삭제
DELETE {{baseUrl}}/comments/3
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###상품 + 이미지
POST {{baseUrl}}/products
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="name"

실전 멀터 상품
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

Multer 다중 이미지 업로드 테스트 상품입니다.
------WebKitFormBoundary
Content-Disposition: form-data; name="price"

1200000
------WebKitFormBoundary
Content-Disposition: form-data; name="tags"

["전자제품", "노트북"]
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="test01.jpg"
Content-Type: image/jpeg

< ./src/test01.jpg
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="test02.jpg"
Content-Type: image/jpeg

< ./src/test02.jpg
------WebKitFormBoundary--

###상품 수정
PATCH {{baseUrl}}/products/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc4MzEzMjgzNywiZXhwIjoxNzgzMTM2NDM3fQ.gEhUsXdLFP1n_1Cbxy15-2tMGHtM6y3k7tXYdT1_o5Y
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="description"

수정 완료! 미개봉 맥북 에어 싸게 넘깁니다.
------WebKitFormBoundary
Content-Disposition: form-data; name="price"

1150000
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="test02.jpg"
Content-Type: image/jpeg

< ./src/test02.jpg
------WebKitFormBoundary--